---
- name: updateub
  hosts: ub
  become: yes

  tasks:
  - name: install httpd
    package:
      name: apache2
      state: present
  - name: start httpd
    service:
      name: apache2
      state: started
  - name: start httpd
    service:
      name: apache2
      enabled: yes
